// twitch-bingo-extension/src/components/VideoOverlay/TabWidget.svelte
<script lang="ts">
import BingoLogo from "../../../assets/BingoLogo.svg"

export let shown:boolean
export let canModerate:boolean
export let hasModNotifications:boolean
export let onToggleGrid: () => void
export let onToggleModerationPane: () => void
</script>

<style lang="scss">
    @import "./TabWidget.scss"
</style>

<div class="tabWidgetContainer">
    <div class:shown class:hidden={!shown} class="tabWidget" on:click|capture={_ => onToggleGrid()}>
        <img src={BingoLogo} alt="Bingo Logo" />
    </div>
    {#if canModerate}
        <div class:pending={hasModNotifications} class="tabWidget" on:click|capture={_ => onToggleModerationPane()}>
            <span>⚔</span>
        </div>
    {/if}
</div>

// twitch-bingo-extension/src/components/VideoOverlay/TabWidget.tsx
import React from "react"
import clsx from 'clsx';
require('./TabWidget.scss')
const BingoLogo = require('../../../assets/BingoLogo.svg')

type VideoOverlayTabWidgetProps = {
    shown: boolean,
    collapsed: boolean,
    canModerate: boolean,
    onToggleGrid: (e: React.MouseEvent<any>) => void,
    onToggleModerationPane: (e: React.MouseEvent<any>) => void,
    hasModNotifications?: boolean,
}

export default function VideoOverlayTabWidget(props: VideoOverlayTabWidgetProps) {
    var moderationWidget: React.ReactElement = null;
    if (props.canModerate)
    {
        moderationWidget = (
            <div onClickCapture={props.onToggleModerationPane} className={clsx(props.hasModNotifications ? "pending" : "", "tabWidget", props.shown ? "shown" : "hidden")}>
                <span style={{fontSize: '2rem'}}>⚔</span>
            </div>
        )
    }

    return (
        <div>
            <div className={clsx("tabWidget", props.shown ? "shown" : "hidden")} onClickCapture={props.onToggleGrid}>
                <img src={BingoLogo} alt="Bingo Logo" />
            </div>
            { moderationWidget }
        </div>
    )
}
