// twitch-bingo-extension/src/components/VideoOverlay/VideoOverlay.svelte
<script lang="ts">
    import TabWidget from "./TabWidget.svelte";
    import type { BingoGameContext } from "../../common/BingoGameContext"
    import { ParseTimespan, type BingoGame, type BingoGrid, type BingoTentativeNotification } from "../../EBS/BingoService/EBSBingoTypes";
    import OverlayBingoGrid from "./OverlayBingoGrid.svelte";
    import LL from '../../i18n/i18n-svelte';
    import BingoGameComponent from "../../common/BingoGameComponent.svelte";
    import type { Writable } from "svelte/store";
    import { onMount, setContext } from "svelte";
    import { createGameContext, GameContextKey } from "../../stores/game"
    import type { BingoGridContext } from "../../common/BingoGridContext";
    import { createGridContext, GridContextKey } from "../../stores/grid";
    import { TwitchExtHelper } from "../../common/TwitchExtension";

    let isCollapsed = true
    let isShowingIdentityPrompt = false
    let isWidgetShown = true
    let hasModNotifications = false
    let moderationDrawerOpen = false
    let isModDrawerAutoOpened = false
    let confirmationTimeout:number = 0.0

    const gameContext:Writable<BingoGameContext> = createGameContext()
    setContext(GameContextKey, gameContext)
    const gridContext:Writable<BingoGridContext> = createGridContext()
    setContext(GridContextKey, gridContext)

    $: confirmationTimeout = ParseTimespan($gameContext.game?.confirmationThreshold ?? "00:00:00")
    
    let layoutClass = "wide"

    onMount(() => {
        TwitchExtHelper.onContext((context, _) => {
            isWidgetShown = (context.arePlayerControlsVisible !== false)
            return () => {
                TwitchExtHelper.onContext(null)
            }
        })
    })

    function onTentativeNotification(_tentative: BingoTentativeNotification) {
        if (!moderationDrawerOpen)
        {
            isModDrawerAutoOpened = true
            moderationDrawerOpen = true
        }
        hasModNotifications = true
    }

    function onNotificationsEmpty() {
        if (isModDrawerAutoOpened)
        {
            moderationDrawerOpen = false
        }
        hasModNotifications = false
    }

    function drawingAreaClick() {
        if (! isCollapsed)
        {
            isCollapsed = true
        }
    }

    function onToggleGrid(gameContext:BingoGameContext)
    {
        if (gameContext === undefined)
        {
            return;
        }
        if (! gameContext.hasSharedIdentity)
        {
            isShowingIdentityPrompt = !isShowingIdentityPrompt
            return
        }
        isShowingIdentityPrompt = false
        isCollapsed = !isCollapsed
        console.log(isCollapsed ? "collapsed" : "not collapsed")
    }

    function onToggleModerationPane() {
        moderationDrawerOpen = !moderationDrawerOpen
        isModDrawerAutoOpened = false
        console.log(`Moderation pane ${moderationDrawerOpen ? "open" : "closed" }`)
    }

    function onSharedIdentityChange(isShared: boolean) {
        if (isShared && isShowingIdentityPrompt) {
            isShowingIdentityPrompt = false
        }
        if (!isShared && !isCollapsed) {
            isCollapsed = true
        }
    }

    function onReceiveGame(game: BingoGame) {
        console.log("Game received")
        if (game)
        {
            if (game.columns < 4)
            {
                layoutClass = "tall"
            }
            else
            {
                layoutClass = "wide"
            }
        }
    }

    function onRefreshGrid(grid: BingoGrid) {
        console.log("Grid refreshed")
    }
</script>

<style lang="scss">
    @use "../../common/BingoStyles.scss";
    @use "./VideoOverlay.scss";
</style>

<BingoGameComponent
    onReceiveGame={onReceiveGame}
    onRefreshGrid={onRefreshGrid}
    onSharedIdentity={onSharedIdentityChange}>
{#if $gameContext}
<!-- svelte-ignore a11y-no-static-element-interactions -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div id="bingoRenderingArea" class={layoutClass}>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <div id="safeAreaTop" style="grid-column-start: 1; grid-column-end: 4; grid-row: 1; height: '14vh'; width: '100%';" on:click|self={drawingAreaClick}></div>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <div class="action-area"
         class:moderationOpen={moderationDrawerOpen}
         style:grid-column="1"
         style:grid-row="2"
         style:height="75vh"
         on:click|self={drawingAreaClick}>
        <div style:grid-column="2" style:grid-row="1">
            <TabWidget
                shown={isWidgetShown}
                bind:moderationShown={moderationDrawerOpen}
                canModerate={$gameContext.canModerate}
                hasModNotifications={hasModNotifications}
                onToggleGrid={() => onToggleGrid($gameContext)} />
        </div>
        <div style:grid-column="1" style:grid-row="1">
            {#if $gameContext.canModerate}
                {#await import('./ModerationSection.svelte') then {default: ModerationSection }}
                    <ModerationSection
                        bind:open={moderationDrawerOpen}
                        confirmationTimeout={confirmationTimeout}
                        onReceiveTentative={onTentativeNotification}
                        onNotificationsEmpty={onNotificationsEmpty}
                    />
                {/await}
            {/if}
        </div>
    </div>
    <div id="bingoGridArea"
        style:grid-column="2"
        style:grid-row="2"
        style:width="1fr"
        style:margin-left="2vw"
        style:height="76vh"
        style:overflow="hidden">
        {#if isShowingIdentityPrompt }
            <div class="identityPrompt">
                    <div style:margin-bottom="2rem" style:margin-top="1rem">
                        {$LL.OverlayBingoGrid.IdentityPromptMessage()}
                    </div>
                    <!-- svelte-ignore a11y-click-events-have-key-events -->
                    <div
                        class="bandeauPrompt bandeauPromptVisible"
                        style:position="unset"
                        on:click={(_) => $gameContext.promptIdentity()}>
                        {$LL.OverlayBingoGrid.ShareIdentityButtonLabel()}
                    </div>
                </div>
        {/if}
        <OverlayBingoGrid
            isCollapsed={isCollapsed}
            layoutClass={layoutClass}
        />
    </div>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <div style:grid-column="3" style:grid-row="2" style:width="7rem" style:height="75vh" on:click={drawingAreaClick}>
    </div>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <div id="safeAreaBottom" style:grid-column-start="1" style:grid-column-end="4" style:grid-row="3" style:height="9vh" style:width="100%" on:click={drawingAreaClick}></div>
</div>
{/if}
</BingoGameComponent>

// twitch-bingo-extension/src/components/VideoOverlay/VideoOverlay.tsx
import React from 'react';
import { Suspense } from 'react';
import clsx from 'clsx';
import BingoGameComponent, { ActiveGameContext } from '../../common/BingoGameComponent';
import { BingoGameContext } from '../../common/BingoGameContext';
import BingoGameModerationComponent, { ActiveGameModerationContext } from '../../common/BingoGameModerationComponent';
import { getRGB, jasminePalette } from '../../common/BingoThemes';
import LinearIndeterminateLoader from '../../common/LinearIndeterminateLoader';
import { TwitchExtHelper } from '../../common/TwitchExtension';
import { BingoTentativeNotification, ParseTimespan } from '../../EBS/BingoService/EBSBingoTypes';
import { I18nContext } from '../../i18n/i18n-react';
import OverlayBingoGrid from './OverlayBingoGrid';
const ModerationPane = React.lazy(() => import('./ModerationPane'));
import VideoOverlayTabWidget from './TabWidget';
require('./VideoOverlay.scss');
require('../../common/BingoStyles.scss');
require('../../common/BingoViewerEntry.scss');

export default function VideoOverlay()
{
    const { LL } = React.useContext(I18nContext)
    
    const [isCollapsed, setCollapsed] = React.useState(true)
    const [moderationDrawerOpen, setModerationDrawerOpen] = React.useState(false)
    const [isWidgetShown, setWidgetShown] = React.useState(true)
    const [hasModNotifications, setHasModNotifications] = React.useState(false)
    const [isModDrawerAutoOpened, setModDrawerAutoOpened] = React.useState(false)
    const [isShowingIdentityPrompt, setShowingIdentityPrompt] = React.useState(false)

    React.useEffect(() => {
        const onContext = (context, _) => {
            setWidgetShown(context.arePlayerControlsVisible !== false)
        }
        TwitchExtHelper.onContext(onContext)
        return () => {
            TwitchExtHelper.onContext(null)
        }
    }, [])
    

    const onTentativeNotification = (_tentative: BingoTentativeNotification) => {
        if (!moderationDrawerOpen)
        {
            setModDrawerAutoOpened(true)
            setModerationDrawerOpen(true)
        }
        setHasModNotifications(true)
    }

    const onNotificationsEmpty = () => {
        if (isModDrawerAutoOpened)
        {
            setModerationDrawerOpen(false)
        }
        setHasModNotifications(false)
    }

    const drawingAreaClick = React.useCallback((_) => {
        if (! isCollapsed)
        {
            setCollapsed(true);
        }
    }, [isCollapsed])

    const onToggleGrid = React.useCallback((gameContext: BingoGameContext) => {
        if (!gameContext.hasSharedIdentity){
            setShowingIdentityPrompt(!isShowingIdentityPrompt)
            return
        }
        setShowingIdentityPrompt(false);
        setCollapsed(!isCollapsed)
    }, [isCollapsed, isShowingIdentityPrompt])

    const onSharedIdentityChange = React.useCallback((isShared: boolean) => {
        if (isShared && isShowingIdentityPrompt)
        {
            setShowingIdentityPrompt(false)
        }
        if (!isShared && !isCollapsed)
        {
            setCollapsed(true)
        }
    }, [isShowingIdentityPrompt, isCollapsed])

    return (
        <BingoGameComponent onSharedIdentity={onSharedIdentityChange}>
            <ActiveGameContext.Consumer>
                {
                    gameContext => {
                        var layoutClass = ""
                        if (gameContext.game)
                        {
                            if (gameContext.game.columns < 4)
                            {
                                layoutClass = "tall"
                            }
                            else
                            {
                                layoutClass = "wide"
                            }
                        }

                        var moderationDrawer: JSX.Element = null;
                        if (gameContext.canModerate)
                        {
                            moderationDrawer = (
                                <Suspense fallback={<LinearIndeterminateLoader />}>
                                    <BingoGameModerationComponent
                                        onReceiveTentative={onTentativeNotification}
                                        onNotificationsEmpty={onNotificationsEmpty} >
                                        <ActiveGameModerationContext.Consumer>
                                            {
                                                moderationContext => {
                                                    return (
                                                        <ModerationPane
                                                            game={gameContext.game}
                                                            tentatives={moderationContext.tentatives}
                                                            isOpen={moderationDrawerOpen}
                                                            isStarted={gameContext.isStarted}
                                                            onOpen={() => {setModerationDrawerOpen(true)}}
                                                            onClose={(_) => {setModerationDrawerOpen(false)}}
                                                            gameId={gameContext.game?.gameId}
                                                            confirmationTimeout={ParseTimespan(gameContext.game?.confirmationThreshold ?? "00:00:00")}
                                                            onReceiveTentative={onTentativeNotification}
                                                            onNotificationsEmpty={onNotificationsEmpty}
                                                            onTentativeExpire={moderationContext.onTentativeExpire} />
                                                    )
                                                }
                                            }
                                        </ActiveGameModerationContext.Consumer>
                                    </BingoGameModerationComponent>
                                </Suspense>
                            )
                        }
                
                        return [
                            <div id="bingoRenderingArea" className={layoutClass}>
                                <div id="safeAreaTop" style={{ gridColumnStart: 1, gridColumnEnd: 4, gridRow: 1, height: '14vh', width: '100%' }} onClickCapture={drawingAreaClick}></div>
                                <div style={{ gridColumn: 1, gridRow: 2, height: '75vh' }} onClickCapture={drawingAreaClick}>
                                    <VideoOverlayTabWidget
                                        shown={isWidgetShown}
                                        collapsed={isCollapsed}
                                        canModerate={gameContext.canModerate}
                                        hasModNotifications={hasModNotifications}
                                        onToggleGrid={() => onToggleGrid(gameContext)}
                                        onToggleModerationPane={(_) => {setModerationDrawerOpen(!moderationDrawerOpen)}} />
                                    { gameContext.canModerate ? moderationDrawer : null }
                                </div>
                                <div id="bingoGridArea" style={{ gridColumn: 2, gridRow: 2, width: '1fr', marginLeft: '2vw', height: '76vh', overflow: 'hidden' }}>
                                    {
                                        isShowingIdentityPrompt ? (
                                            <div style={
                                                {
                                                    backgroundColor: getRGB(jasminePalette.base),
                                                    width: '100%',
                                                    textAlign: 'center',
                                                    paddingTop: '1vw',
                                                    paddingBottom: '1vw',
                                                    borderRadius: '0.25vw',
                                                    transition: 'opacity 0.5s',
                                                }}>
                                                <div style={{marginBottom: '2rem', marginTop: '1rem'}}>
                                                    {LL.OverlayBingoGrid.IdentityPromptMessage()}
                                                </div>
                                                <div
                                                    className={clsx("bandeauPrompt", "bandeauPromptVisible")}
                                                    style={{position: 'unset'}}
                                                    onClickCapture={(_) => gameContext.promptIdentity()}>
                                                    {LL.OverlayBingoGrid.ShareIdentityButtonLabel()}
                                                </div>
                                            </div>
                                        ) : null
                                    }
                                    <OverlayBingoGrid
                                        isCollapsed={isCollapsed}
                                    />
                                </div>
                                <div style={{ gridColumn: 3, gridRow: 2, width: '7rem', height: '75vh' }} onClickCapture={drawingAreaClick}>
                                </div>
                                <div id="safeAreaBottom" style={{ gridColumnStart: 1, gridColumnEnd: 4, gridRow: 3, height: '9vh', width: '100%' }} onClickCapture={drawingAreaClick}></div>
                            </div>
                        ];
                    }
                }
            </ActiveGameContext.Consumer>
        </BingoGameComponent>
    )
}
