// twitch-bingo-extension/src/common/BingoGameComponent.tsx
import * as React from 'react';
import { TwitchExtHelper } from './TwitchExtension';
import { BingoEntryState, BingoGridCell, BingoPendingResult } from '../model/BingoEntry';
import { BingoEBS } from '../EBS/BingoService/EBSBingoService';
import { Twitch } from '../services/TwitchService';
import { BingoConfirmationNotification, BingoEntry, BingoGame, BingoGrid, ParseTimespan } from '../EBS/BingoService/EBSBingoTypes';
import { BingoGameContext } from './BingoGameContext';
import { BingoGridContext } from './BingoGridContext';
import { BingoBroadcastEvent, BingoBroadcastEventType, BingoConfiguration } from '../model/BingoConfiguration';

export const ActiveGameContext = React.createContext<BingoGameContext>(null)
export const ActiveGridContext = React.createContext<BingoGridContext>(null)

type BingoGameComponentProps = {
    children?: React.ReactNode,
    onRefreshGrid?: (grid: BingoGrid, cells: BingoGridCell[]) => void,
    onReceiveGame?: (game: BingoGame) => void,
    onStop?: () => void,
    onSharedIdentity?: (isShared: boolean) => void,
}

export default function BingoGameComponent(props: BingoGameComponentProps) {
    const [entries, setEntries] = React.useState<BingoEntry[]>(new Array(0))
    const [canModerate, setCanModerate] = React.useState(false)
    const [canVote, setCanVote] = React.useState(false)
    const [pendingResults, setPendingResults] = React.useState<BingoPendingResult[]>(new Array(0))
    const [activeGame, setActiveGame] = React.useState<BingoGame>(null)
    const [isStarted, setStarted] = React.useState(false)
    const [grid, setGrid] = React.useState<BingoGrid>(null)
    const [hasSharedIdentity, setSharedIdentity] = React.useState(false)
    const [isAuthorized, setAuthorized] = React.useState(false)

    const onLoadConfig = React.useCallback((configContent: BingoConfiguration) => {
        const activeGameId: string = configContent.activeGameId ?? configContent.activeGame?.gameId
        if (activeGame?.gameId !== activeGameId)
        {
            BingoEBS.getGame(activeGameId)
                .then(game => {
                    setActiveGame(game)
                    onStart(game)
                    if (props.onReceiveGame)
                    {
                        props.onReceiveGame(configContent.activeGame);
                    }
                })
                .catch(error => {
                    console.log(`Error fetching game ${activeGameId}: ${error}`)
                })
        }
    }, [activeGame])

    const loadConfig = (_broadcasterConfig: any) => {
        var extensionConfig = Twitch.configuration;
        if (! extensionConfig?.content)
        {
            return;
        }
        var configContent: BingoConfiguration = JSON.parse(extensionConfig.content);
        onLoadConfig(configContent)
    }

    React.useEffect(() => {
        Twitch.onConfiguration.push(loadConfig);
        return () => {
            var index = Twitch.onConfiguration.indexOf(loadConfig)
            if (index !== -1)
            {
                Twitch.onConfiguration.splice(index, 1)
            }
        }
    }, [])

    const receiveBroadcast = React.useCallback((_target, _contentType, messageStr) => {
        let message: BingoBroadcastEvent = JSON.parse(messageStr);
        switch (message.type) {
            case BingoBroadcastEventType.SetConfig:
                let config: BingoConfiguration = message.payload
                if (config.activeGame)
                {
                    setActiveGame(message.payload.activeGame)
                    // console.log(config.activeGame);
                }
                onLoadConfig(config)
                break;
            case BingoBroadcastEventType.Start:
                setActiveGame(message.payload)
                onStart(message.payload);
                break;
            case BingoBroadcastEventType.Bingo:
                refreshGrid(activeGame, null);
                break;
            case BingoBroadcastEventType.Stop:
                setPendingResults(new Array(0))
                setGrid(null)
                setEntries(new Array(0))
                setActiveGame(null)
                console.log("Stopped game");
                if (props.onStop)
                {
                    props.onStop()
                }
                break;
            case BingoBroadcastEventType.Confirm:
                onConfirmationNotification(message.payload)
                break;
            default:
                break;
        }
    }, [activeGame, entries])

    React.useEffect(() => {
        TwitchExtHelper.listen('broadcast', receiveBroadcast);
        return () => {
            TwitchExtHelper.unlisten('broadcast', receiveBroadcast)
        }
    }, [activeGame])

    const onAuthorized = React.useCallback((_context) => {
        setCanModerate(TwitchExtHelper.viewer.role == 'broadcaster' || TwitchExtHelper.viewer.role == 'moderator')
        setCanVote(TwitchExtHelper.viewer.role != 'external')
        setSharedIdentity(TwitchExtHelper.viewer.isLinked)
        setAuthorized(true)
        if (activeGame)
        {
            refreshGame(activeGame)
        }
        if (props.onSharedIdentity)
        {
            props.onSharedIdentity(TwitchExtHelper.viewer.isLinked)
        }
    }, [activeGame])

    React.useEffect(() => {
        Twitch.onAuthorized.push(onAuthorized)
        return () => {
            var index = Twitch.onAuthorized.findIndex(onAuthorized)
            if (index !== -1)
            {
                Twitch.onAuthorized.splice(index, 1)
            }
        }
    }, [])

    React.useEffect(() => {
        if (canModerate && activeGame)
        {
            refreshGame(activeGame)
        }
    }, [canModerate])

    const refreshGame = React.useCallback((game: BingoGame) => {
        if (canModerate)
        {
            BingoEBS.getGame(game.gameId).then(refreshedGame => {
                // console.log("Refreshed game for moderation")
                setActiveGame(refreshedGame)
            }).catch(error => {
                console.error("Error loading game from EBS: " + error);
            });
        }
    }, [canModerate])

    const refreshGrid = React.useCallback((game: BingoGame, refreshEntries: BingoEntry[]) => {
        if (! game)
        {
            console.error("No game provided to refreshGrid")
            return
        }
        if (! isAuthorized)
        {
            console.error("Unidentified user, aborting refresh")
            return
        }
        BingoEBS.getGrid(game.gameId).then(grid => {
            // console.log(`Refreshing grid.`)
            if (refreshEntries)
            {
                // console.log(`Refreshing entries: ${JSON.stringify(refreshEntries)}`)
                setEntries(refreshEntries)
            }
            setGrid(grid)
        }).catch(error => {
            console.error("Error loading grid from EBS: " + error);
        });
        setActiveGame(game)
        refreshGame(game)
    }, [isAuthorized])

    React.useEffect(() => {
        if (grid && props.onRefreshGrid) props.onRefreshGrid(grid, grid.cells.map(c => getCell(c.row, c.col)[0]))
    }, [grid])

    const onStart = (payload: BingoGame) => {
        // console.log("Received start for game:" + payload.gameId);
        refreshGrid(payload, payload.entries);
        setStarted(true)
    };

    const onTentativeRefresh = React.useCallback((entry: BingoEntry) => {
        console.log(`onTentative, refreshing grid after timeout ${entries.length}`);
        setPendingResults(pendingResults.filter(p => p.key != entry.key))
        refreshGrid(activeGame, null);
    }, [activeGame, entries, pendingResults])

    const onTentative = React.useCallback((entry: BingoEntry) => {  
        BingoEBS.tentative(activeGame.gameId, entry.key.toString());
        var cellIndex = grid.cells.findIndex(c => c.key == entry.key);
        grid.cells[cellIndex].state = BingoEntryState.Pending;
        var pendingResultsRefreshed:BingoPendingResult[] = pendingResults.filter(p => p.key != entry.key);

        var confirmationTimeout = ParseTimespan(activeGame.confirmationThreshold) + 500

        pendingResultsRefreshed.push({
            key: entry.key,
            expireAt: new Date(Date.now() + confirmationTimeout),
        });
        setGrid(grid)
        setPendingResults(pendingResultsRefreshed)

        setTimeout(() => onTentativeRefresh(entry), confirmationTimeout);
        console.log(`onTentative, updated cell state, set countdown to ${pendingResultsRefreshed[pendingResultsRefreshed.length - 1].expireAt} - ${entries.length}`);
    }, [grid, pendingResults, activeGame, entries]);

    if (props.onRefreshGrid)
    {
        React.useEffect(() => {
            if (grid?.cells)
            {
                props.onRefreshGrid(grid, grid.cells.map(c => getCell(c.row, c.col)[0]))
            }
        }, [grid, pendingResults])
    }

    const getCell = React.useCallback((row: number, col: number): [BingoGridCell,BingoEntry] => {
        var cellResult = grid.cells.filter(c => c.row === row && c.col === col);
        if (cellResult.length == 1)
        {
            var cell = cellResult[0];
            var entryResult = entries.filter(e => e.key === cell.key);
            if (entryResult.length == 1)
            {
                var entry = entryResult[0];
                var pending: BingoPendingResult = pendingResults.find(p => p.key == cell.key);
                return [
                    {
                        row: row,
                        col: col,
                        key: entry.key,
                        text: entry.text,
                        state: cell.state,
                        timer: pending?.expireAt,
                    },
                    entry
                ];
            }
            else
            {
                console.error(`Error fetching cell entry #${cell.key} at (r${row},c${col}), result: ${JSON.stringify(entryResult)}`)
                console.error(`Entries : ${JSON.stringify(entries)}`)
            }
        }
        else
        {
            console.error(`Error fetching cell at (r${row},c${col}), result: ${JSON.stringify(cellResult)}`)
        }
        return [
            {
                row: row,
                col: col,
                key: -(col + (row * grid.cols)) - 1,
                text: "",
                state: BingoEntryState.Idle,
                timer: null,
            },
            null
        ];
    }, [grid, entries, pendingResults]);

    const isColComplete = React.useCallback((col: number): boolean =>
    {
        return grid.cells.filter(c => c.col == col).every(c => c.state == BingoEntryState.Confirmed);
    }, [grid])

    const isRowComplete = React.useCallback((row: number): boolean => {
        return grid.cells.filter(c => c.row == row).every(c => c.state == BingoEntryState.Confirmed);
    }, [grid])
    
    const onConfirmationNotification = React.useCallback((confirmation: BingoConfirmationNotification) => {
        // console.log(confirmation)
        setEntries(currentEntries => {
            return currentEntries.map(entry => {
                if (entry.key === confirmation.key)
                {
                    return {
                        key: confirmation.key,
                        text: entry.text,
                        confirmedAt: confirmation.confirmationTime,
                        confirmedBy: confirmation.confirmedBy,
                    }
                }
                return entry
            })
        })
    }, [entries])

    const promptIdentity = (): void => {
        console.log("Prompting identity")
        TwitchExtHelper.actions.requestIdShare()
    }

    return (
        <ActiveGameContext.Provider value={
                {
                    isAuthorized: isAuthorized,
                    isStarted: isStarted,
                    hasSharedIdentity: hasSharedIdentity,
                    promptIdentity: promptIdentity,
                    game: activeGame,
                    onTentative: onTentative,
                    canModerate: canModerate,
                    canVote: canVote
                }
            }>
            <ActiveGridContext.Provider value={
                    {
                        grid: grid,
                        getCell: getCell,
                        isColComplete: isColComplete,
                        isRowComplete: isRowComplete
                    }
                }>
                { props.children }
            </ActiveGridContext.Provider>
        </ActiveGameContext.Provider>
    )
}

// twitch-bingo-extension/src/common/BingoGameComponent.svelte
<script lang="ts">
    import { DefaultEntry, ParseTimespan, type BingoConfirmationNotification, type BingoEntry, type BingoGame, type BingoGrid } from "../EBS/BingoService/EBSBingoTypes";
    import { type Writable } from "svelte/store";
    import { getContext, onMount } from "svelte";
    import { BingoEntryState, BingoPendingResult, type BingoGridCell } from "../model/BingoEntry";
    import { BingoBroadcastEventType, type BingoBroadcastEvent, type BingoConfiguration } from "../model/BingoConfiguration";
    import { BingoEBS } from "../EBS/BingoService/EBSBingoService";
    import { Twitch } from "../services/TwitchService";
    import { TwitchExtHelper } from "./TwitchExtension";
    import { GameContextKey, setGame } from "../stores/game";
    import { GridContextKey, setGrid } from "../stores/grid";
    import type { BingoGameContext } from "./BingoGameContext";
    import type { BingoGridContext } from "./BingoGridContext";

    export let onRefreshGrid: (grid: BingoGrid, cells: BingoGridCell[]) => void = (a,b) => {}
    export let onReceiveGame: (game: BingoGame) => void = (g) => {}
    export let onStop: () => void = () => {}
    export let onSharedIdentity: (isShared:boolean) => void

    const gameContext: Writable<BingoGameContext> = getContext(GameContextKey)
    const gridContext: Writable<BingoGridContext> = getContext(GridContextKey)
    

    let isStarted:boolean = false
    let entries:BingoEntry[] = Array(0)
    let canModerate:boolean = false
    let canVote:boolean = false
    let isAuthorized:boolean = false
    let hasSharedIdentity = false;
    
    Twitch.onAuthorized.push((context) => {
        isAuthorized = true;
        canModerate = TwitchExtHelper.viewer.role == 'broadcaster' || TwitchExtHelper.viewer.role == 'moderator'
        canVote = TwitchExtHelper.viewer.role != 'external'
        hasSharedIdentity = TwitchExtHelper.viewer.isLinked
        if (onSharedIdentity)
        {
            onSharedIdentity(TwitchExtHelper.viewer.isLinked)
        }
        gameContext.update(gc => {
            gc.canModerate = canModerate
            gc.canVote = gc.canVote
            gc.isAuthorized = isAuthorized
            gc.hasSharedIdentity = hasSharedIdentity
            gc.requestRefresh = (id: string) => {
                refreshGrid(id, null)
            }
            return gc
        })
    })

    let pendingResults:BingoPendingResult[] = new Array(0)

    gameContext.subscribe(context => {
        if (context.game) onReceiveGame(context.game)
    })
    gridContext.subscribe(context => onRefreshGrid(context.grid, context.grid.cells.map(c => getCell(c.row, c.col)[0])))

    
    function onConfirmationNotification(confirmation: BingoConfirmationNotification) {
        // console.log(confirmation)
        entries = entries.map(entry => {
                if (entry.key === confirmation.key)
                {
                    return {
                        key: confirmation.key,
                        text: entry.text,
                        confirmedAt: confirmation.confirmationTime,
                        confirmedBy: confirmation.confirmedBy,
                    }
                }
                return entry
            })
        pendingResults = pendingResults.filter(p => p.key != confirmation.key)
    }
    
    function receiveBroadcast(_target: any, _contentType: any, messageStr: string) {
        console.log(`Received broadcast: ${messageStr}`)
        let message: BingoBroadcastEvent = JSON.parse(messageStr);
        switch (message.type) {
            case BingoBroadcastEventType.SetConfig:
                let config: BingoConfiguration = message.payload
                if (config.activeGame)
                {
                    gameContext.update(gc => {
                        gc.game = config.activeGame
                        return gc
                    })
                }
                onLoadConfig(config)
                break;
            case BingoBroadcastEventType.Start:
                onStart(message.payload);
                break;
            case BingoBroadcastEventType.Bingo:
                if ($gameContext.game)
                {
                    refreshGrid($gameContext.game.gameId, null);
                }
                break;
            case BingoBroadcastEventType.Stop:
                pendingResults = new Array(0)
                entries = new Array(0)
                gameContext.update(gc => {
                    gc.game = undefined
                    return gc
                })
                console.log("Stopped game");
                if (onStop)
                {
                    onStop()
                }
                break;
            case BingoBroadcastEventType.Confirm:
                onConfirmationNotification(message.payload)
                break;
            default:
                break;
        }
    }

    onMount(() => {
        TwitchExtHelper.listen('broadcast', receiveBroadcast);
        return () => {
            TwitchExtHelper.unlisten('broadcast', receiveBroadcast)
        }
    })


    const onStart = (payload: BingoGame) => {
        refreshGrid(payload.gameId, payload.entries)
        gameContext.update(gc => {
            gc.isStarted = true
            gc.onTentative = onTentative
            return gc
        })
        isStarted = true
    }

    const refreshGrid = (gameId: string, refreshEntries: BingoEntry[] | null) => {
        if (! gameId)
        {
            console.error("No game provided to refreshGrid")
            return
        }
        if (! isAuthorized)
        {
            console.error("Unidentified user, aborting refresh")
            return
        }
        BingoEBS.getGrid(gameId).then(grid => {
            console.log(`Refreshing grid.`)
            if (refreshEntries)
            {
                console.log(`Refreshing entries: ${JSON.stringify(refreshEntries)}`)
                entries = refreshEntries
            }
            setGrid(gridContext, grid)
        }).catch(error => {
            console.error("Error loading grid from EBS: " + error);
        });
        // setGame(gameContext, game)
        refreshGame(gameId)
    }

    const refreshGame = (gameId: string) => {
        if ($gameContext.canModerate)
        {
            BingoEBS.getGame(gameId).then(refreshedGame => {
                console.log("Refreshed game for moderation")
                setGame(gameContext, refreshedGame)
            }).catch(error => {
                console.error("Error loading game from EBS: " + error);
            });
        }
    }

    const loadConfig = (_broadcasterConfig: any) => {
        var extensionConfig = Twitch.configuration;
        if (! extensionConfig?.content)
        {
            return;
        }
        var configContent: BingoConfiguration = JSON.parse(extensionConfig.content);
        onLoadConfig(configContent)
    }

    Twitch.onConfiguration.push(loadConfig)

    let onLoadConfig = (configContent: BingoConfiguration) => {
        const activeGameId:string = configContent.activeGameId ?? configContent.activeGame?.gameId ?? ""
        if ($gameContext.game?.gameId !== activeGameId)
        {
            BingoEBS.getGame(activeGameId)
                .then(game => {
                    setGame(gameContext, game)
                    onStart(game)
                    if (onReceiveGame)
                    {
                        onReceiveGame(game)
                    }
                })
                .catch(error => {
                    console.log(`Error fetching game ${activeGameId}: ${JSON.stringify(error)}`)
                })
        }
    }

    const getCell = (row: number, col: number):[BingoGridCell,BingoEntry] => {
        var cellResult = $gridContext.grid.cells.filter(c => c.row === row && c.col === col);
        if (cellResult.length == 1)
        {
            var cell = cellResult[0];
            var entryResult = entries.filter(e => e.key === cell.key);
            if (entryResult.length == 1)
            {
                var entry = entryResult[0];
                var pending: BingoPendingResult | undefined = pendingResults.find(p => p.key == cell.key);
                return [
                    {
                        row: row,
                        col: col,
                        key: entry.key,
                        text: entry.text,
                        state: cell.state,
                        timer: pending?.expireAt ?? null,
                    },
                    entry
                ];
            }
            else
            {
                console.error(`Error fetching cell entry #${cell.key} at (r${row},c${col}), result: ${JSON.stringify(entryResult)}`)
                console.error(`Entries : ${JSON.stringify(entries)}`)
            }
        }
        else
        {
            console.error(`Error fetching cell at (r${row},c${col}), result: ${JSON.stringify(cellResult)}`)
        }
        return [
            {
                row: row,
                col: col,
                key: -(col + (row * $gridContext.grid.cols)) - 1,
                text: "",
                state: BingoEntryState.Idle,
                timer: null,
            },
            DefaultEntry
        ]
    }

    const onTentativeRefresh = (entry: BingoEntry) => {
        console.log(`onTentative, refreshing grid after timeout ${entries.length}`);
        
        pendingResults = pendingResults.filter(p => p.key != entry.key)
        refreshGrid($gameContext.game!.gameId, null);
    }
    
    const onTentative = (entry: BingoEntry) => {  
        if ($gameContext.game)
        {
            BingoEBS.tentative($gameContext.game.gameId, entry.key.toString());
            var cellIndex = $gridContext.grid.cells.findIndex(c => c.key == entry.key);
            $gridContext.grid.cells[cellIndex].state = BingoEntryState.Pending;
            var pendingResultsRefreshed:BingoPendingResult[] = pendingResults.filter(p => p.key != entry.key);

            var confirmationTimeout = ParseTimespan($gameContext.game.confirmationThreshold) + 500

            pendingResultsRefreshed.push({
                key: entry.key,
                expireAt: new Date(Date.now() + confirmationTimeout),
            });
            pendingResults = pendingResultsRefreshed
            setTimeout(() => onTentativeRefresh(entry), confirmationTimeout);
            console.log(`onTentative, updated cell state, set countdown to ${pendingResultsRefreshed[pendingResultsRefreshed.length - 1].expireAt} - ${entries.length}`);

            setGrid(gridContext, $gridContext.grid)
        }
    }

    gameContext.update(gc => {
        gc.promptIdentity = (): void => {
            console.log("Prompting identity")
            TwitchExtHelper.actions.requestIdShare()
        }
        return gc
    })

    gridContext.update(gc => {
        gc.getCell = getCell
        return gc
    })

</script>

<slot></slot>
