// twitch-bingo-extension/src/common/BingoViewerEntry.tsx
import React from "react";
import clsx from 'clsx';
import { BingoEntryState } from "../model/BingoEntry";
import { CountdownCircleTimer } from "react-countdown-circle-timer";
import { BingoEntry, FormatTimeout } from "../EBS/BingoService/EBSBingoTypes";
import { I18nContext } from "../i18n/i18n-react";
require('./BingoStyles.scss')
require('./BingoViewerEntry.scss')

type BingoViewerEntryProps = {
    config: BingoEntry,
    state: BingoEntryState,
    canInteract: boolean,
    canConfirm: boolean,
    isRowCompleted: boolean,
    isColCompleted: boolean,
    onTentative: (entry: BingoEntry) => void,
    countdown?: Date,
    fontSize: string,
    isShown: boolean
}

const renderTime = ({remainingTime}) => {
    return FormatTimeout(remainingTime);
}

export default function BingoViewerEntry(props: BingoViewerEntryProps) {
    const { LL } = React.useContext(I18nContext)
    
    const [confirmationPrompt, setConfirmationPrompt] = React.useState(false);

    var showTimer: boolean = props.countdown != null;
    var timerComponent: React.ReactElement = null;
    if (showTimer)
    {
        var duration = (props.countdown.getTime() - Date.now()) / 1000;
        if (duration > 0)
        {
            timerComponent = 
            <div className={clsx("bingoCellPrompt", "bingoCellPromptVisible")} style={{cursor: "unset"}}>
                <div style={{ display: 'inline-block' }}>
                    <CountdownCircleTimer
                        isPlaying
                        size={50}
                        strokeWidth={3}
                        colors="#000"
                        isLinearGradient={true}
                        duration={duration}
                        children={renderTime}
                    />
                </div>
            </div>
        }
    }

    const handlePrompt = (_event: React.MouseEvent<HTMLElement>) => {
        if (! props.isShown)
        {
            return;
        }
        if (confirmationPrompt || props.state == BingoEntryState.Idle)
        {
            setConfirmationPrompt(! confirmationPrompt)
        }
    };

    const handleTentative = (_event: React.MouseEvent<HTMLElement>) => {
        props.onTentative(props.config)
        setConfirmationPrompt(false)
    };

    let stateClass = confirmationPrompt ? "prompt" : "idle";
    switch(props.state)
    {
        case BingoEntryState.Confirmed:
            stateClass = "confirmed";
            break;
        case BingoEntryState.Missed:
            stateClass = "missed";
            break;
        case BingoEntryState.Pending:
            stateClass = "pending";
            break;
        case BingoEntryState.Rejected:
            stateClass = "rejected";
            break;
        default:
            break;
    }
    const entryVariantType = `type${props.config.key % 10}`;

    return (
        <div className={clsx("entryGridCell", entryVariantType)}>
            <div className={clsx(
                                "bingoCell",
                                props.isShown ? "visibleCell" : "hiddenCell",
                                "paper",
                                stateClass,
                                props.isColCompleted ? "colConfirmed" : '',
                                props.isRowCompleted ? "rowConfirmed" : '')}
                onClickCapture={handlePrompt}>
                <div className={clsx("bingoCellOverlay", stateClass)}></div>
                <div className={clsx("bingoEntry")}>
                    <div className={clsx("bingoEntryText")} >
                        {props.config.text}
                    </div>
                </div>
                <div
                    className={clsx("bingoCellPrompt", confirmationPrompt ? "bingoCellPromptVisible" : "bingoCellPromptHidden")}
                    onClickCapture={(props.isShown && confirmationPrompt) ? handleTentative : null} >
                    {LL.BingoViewerEntry.ConfirmButtonLabel()}
                </div>
                { timerComponent }
            </div>
        </div>
    )
}

// twitch-bingo-extension/src/common/BingoViewerEntry.svelte
<script lang="ts">
    import { FormatTimeout, type BingoEntry } from "../EBS/BingoService/EBSBingoTypes";
    import { BingoEntryState } from "../model/BingoEntry";
    import { Moon } from 'svelte-loading-spinners'
    import LL from "../i18n/i18n-svelte";


    export let config: BingoEntry
    export let state: BingoEntryState
    export let isRowCompleted: boolean
    export let isColCompleted: boolean
    export let onTentative: (entry: BingoEntry) => void
    export let countdown: Date = null
    export let fontSize: string
    export let isShown: boolean

    let confirmationPrompt:boolean = false

    function renderTime(remainingTime)
    {
        return FormatTimeout(remainingTime)
    }

    function handlePrompt(_:any) {
        if (!isShown)
        {
            return
        }
        if (confirmationPrompt || state == BingoEntryState.Idle)
        {
            confirmationPrompt = ! confirmationPrompt
        }
    }

    function handleTentative(_:any) {
        onTentative(config)
        confirmationPrompt = false
    }

    let entryVariantType = `type${config.key % 10}`
    let stateClass = confirmationPrompt ? "prompt" : "idle";

    let showTimer = countdown != null
    let duration = 0
    if (showTimer)
    {
        duration = (countdown.getTime() - Date.now()) / 1000
        showTimer &&= duration > 0
    }
</script>

<style lang="scss">
    @import "./BingoViewerEntry.scss"
</style>

<div class={"entryGridCell " + entryVariantType}>
    <div    class={"bingoCell paper " + stateClass}
            class:visibleCell={isShown}
            class:hiddenCell={!isShown}
            class:colConfirmed={isColCompleted}
            class:rowConfirmed={isRowCompleted}
            on:click={handlePrompt}>
        <div class={"bingoCellOverlay " + stateClass}></div>
        <div class="bingoEntry">
            <div class="bingoEntryText" >
                {config.text}
            </div>
        </div>
        <div
            class="bingoCellPrompt" class:bingoCellPromptVisible={confirmationPrompt} class:bingoCellPromptHidden={!confirmationPrompt}
            on:click={(isShown && confirmationPrompt) ? handleTentative : null} >
            {LL.BingoViewerEntry.ConfirmButtonLabel()}
        </div>
        {#if showTimer}
            <div class="countdownPrompt bingoCellPrompt bingoCellPromptVisible">
                <div style="font-size: '16px'">
                    <Moon size="70" color="#EA4E7A" duration={`{duration}s`} unit="px"/>
                    /* <CountdownCircleTimer
                        isPlaying
                        size={70}
                        isLinearGradient={true}
                        duration={duration}
                        children={renderTime}
                        strokeWidth={12}
                        trailColor={"#F4A4BB"}
                        colors={"#EA4E7A"}
                    /> */
                </div>
            </div>
        {/if}
    </div>
</div>
