// twitch-bingo-extension/src/common/ModerationBingoComponent.svelte
<script lang="ts">
    import type { BingoEntry, BingoTentativeNotification } from "src/EBS/BingoService/EBSBingoTypes";
    import Paper from '@smui/paper'

    export let entries: BingoEntry[]
    export let tentatives: BingoTentativeNotification[]
    export let isStarted: boolean
    export let gameId: string
    export let confirmationTimeout: number
    export let onConfirm: (entry: BingoEntry) => void
    export let onTentativeExpire: (entry: BingoEntry) => void
    export let onTest: (entry: BingoEntry) => void | undefined


</script>

<Paper elevation="3">
    <div>
        {#each tentatives as tentative}
        {#if tentative}
            
        {/if}
        {/each}

        
                    props.tentatives.map((tentative) => {
                        if (tentative)
                        {
                            var entry: BingoEntry = props.entries.find(e => e.key == tentative.key);

                            return (
                                <TentativeNotificationComponent
                                    gameId={tentative.gameId}
                                    entry={entry}
                                    isConfirmed={tentative.confirmationTime != null}
                                    referenceTime={tentative.confirmationTime ?? tentative.tentativeTime}
                                    key={tentative.key}
                                    confirmationTimeout={props.confirmationTimeout}
                                    onConfirm={props.onConfirm}
                                    onExpire={props.onTentativeExpire}
                                />
                            );
                        }
                    })
    </div>
</Paper>

// twitch-bingo-extension/src/common/ModerationBingoComponent.tsx
import { Button, ButtonGroup, List, ListItem, ListItemSecondaryAction, ListItemText, Paper } from "@material-ui/core"
import React from "react"
import { BingoEntry, BingoTentativeNotification } from "../EBS/BingoService/EBSBingoTypes"
import TentativeNotificationComponent from "./TentativeNotificationComponent"


type ModerationBingoComponentProps = {
    entries: BingoEntry[],
    tentatives: BingoTentativeNotification[],
    isStarted: boolean,
    gameId: string,
    confirmationTimeout: number,
    onConfirm: (entry: BingoEntry) => void,
    onTentativeExpire: (entry: BingoEntry) => void,
    onTest? : (entry: BingoEntry) => void,
}

export default function ModerationBingoComponent(props: ModerationBingoComponentProps)
{
    return (
        <Paper elevation={3}>
            <List>
                {
                    props.tentatives.map((tentative) => {
                        if (tentative)
                        {
                            var entry: BingoEntry = props.entries.find(e => e.key == tentative.key);

                            return (
                                <TentativeNotificationComponent
                                    gameId={tentative.gameId}
                                    entry={entry}
                                    tentativeTime={tentative.tentativeTime}
                                    key={tentative.key}
                                    confirmationTimeout={props.confirmationTimeout}
                                    onConfirm={props.onConfirm}
                                    onExpire={props.onTentativeExpire}
                                />
                            );
                        }
                    })
                }
            </List>
            <List>
                {
                    props.entries.map((entry) => {
                        const tentative = props.tentatives.find(t => t.key == entry.key)
                        if (tentative)
                        {
                            return null;
                        }
                        
                        return (
                            <ListItem key={entry.key}>
                                <ListItemText primary={entry.text} />
                                <ListItemSecondaryAction>
                                    <ButtonGroup size="small">
                                        <Button aria-label="Confirm" onClick={(_) => props.onConfirm(entry)} >Confirm</Button>
                                        {/* <Button aria-label="Test" onClick={(_) => {if (props.onTest) props.onTest(entry)}}>Test</Button> */}
                                    </ButtonGroup>
                                </ListItemSecondaryAction>
                            </ListItem>
                        );
                    })
                }
            </List>
        </Paper>
    )
}
