// twitch-bingo-extension/src/common/TentativeNotificationComponent.tsx
import Button from "@material-ui/core/Button"
import React from "react"
import clsx from 'clsx'
import { CountdownCircleTimer } from "react-countdown-circle-timer"
import { BingoEntry } from "../EBS/BingoService/EBSBingoTypes"
import { bingoStyles } from "./BingoStyles"

type TentativeNotificationComponentProps = {
    gameId: string,
    entry: BingoEntry,
    onExpire?: (entry: BingoEntry) => void,
    onConfirm: (entry: BingoEntry) => void,
    referenceTime: Date,
    confirmationTimeout: number,
    isConfirmed: boolean,
}

export default function TentativeNotificationComponent(props: TentativeNotificationComponentProps)
{
    const [isConfirmed, setConfirmed] = React.useState(props.isConfirmed);
    const [referenceTime, setReferenceTime] = React.useState<Date>(props.referenceTime);
    const classes = bingoStyles();

    const handleConfirm = (_event: React.MouseEvent<HTMLButtonElement>) => {
        props.onConfirm(props.entry)
        setConfirmed(true)
        setReferenceTime(new Date())
    };

    var duration: number = (referenceTime.getTime() - Date.now()) + props.confirmationTimeout;
    
    return (
        <div key={props.entry.key} className={clsx(isConfirmed ? classes.confirmed : classes.pending)} style={{display: 'grid', gridAutoColumns: 'auto 1fr auto', padding: '0.5rem'}}>
            <div style={{gridColumn: 1, display: 'inline-grid', paddingRight: '1rem'}}>
                <CountdownCircleTimer
                    isPlaying
                    key={isConfirmed ? "pre-confirmation" : "post-confirmation" }
                    size={40}
                    strokeWidth={2}
                    colors="#000"
                    duration={duration/1000}
                    children={renderTime}
                    onComplete={ (_elapsed) => {
                        if (! isConfirmed)
                        {
                            if (props.onExpire) props.onExpire(props.entry)
                        }
                        else
                        {
                            if (props.onExpire) props.onExpire(props.entry)
                        }
                    }}
                />
            </div>
            <div style={{gridColumn: 2, display: 'inline-grid', alignSelf: 'center'}}>
                {props.entry.text}
            </div>
            <div style={{gridColumn: 3, display: 'inline-grid'}}>
                <Button onClick={handleConfirm} disabled={isConfirmed}>Confirm</Button>
            </div>
        </div>
    )
}

const renderTime = ({remainingTime}) => {
    return `${remainingTime}`;
}

// twitch-bingo-extension/src/common/TentativeNotificationComponent.svelte
<script lang="ts">
    import Button from "@smui/button";
    import type { BingoEntry } from "src/EBS/BingoService/EBSBingoTypes";
    import LL from "src/i18n/i18n-svelte";
    import CountdownCircleTimer from "./CountdownCircleTimer.svelte";

    export let gameId: string
    export let entry: BingoEntry
    export let onExpire: (entry: BingoEntry) => void | undefined
    export let onConfirm: (entry: BingoEntry) => void
    export let referenceTime: Date
    export let confirmationTimeout: number
    export let isConfirmed: boolean

    var duration: number = (referenceTime.getTime() - Date.now()) + confirmationTimeout;
    
    const handleConfirm = () => {
        onConfirm(entry)
        isConfirmed = true
        referenceTime = new Date()
    };

    function renderTime (remainingTime: Date) {
        return `${remainingTime}`;
    }
</script>

<div class:confirmed={isConfirmed} class:pending={!isConfirmed} style:diplay="grid" style:grid-auto-columns="auto 1fr auto" style:padding="0.5rem">
    <div style:gridColumn="1" style:display="inline-grid" style:padding-right="1rem">
        <CountdownCircleTimer
            isPlaying
            key={isConfirmed ? "pre-confirmation" : "post-confirmation" }
            size={40}
            strokeWidth={2}
            colors="#000"
            duration={duration/1000}
            children={renderTime}
            onComplete={ (_elapsed) => {
                if (! isConfirmed)
                {
                    if (onExpire) onExpire(entry)
                }
                else
                {
                    if (onExpire) onExpire(entry)
                }
            }}
        />
    </div>
    <div style:grid-column="2" style:display="inline-grid" style:align-self="center">
        {entry.text}
    </div>
    <div style:grid-column="3" style:display="inline-grid">
        <Button aria-label={$LL.BingoModeration.ConfirmButtonLabel()} on:click={handleConfirm} disabled={isConfirmed}>{$LL.BingoModeration.ConfirmButton()}</Button>
    </div>
</div>
