// twitch-bingo-extension/src/components/Mobile/BingoMobileMiniGrid.tsx
import React from 'react'
import { seededRand } from '../../common/ExtensionUtils';
import { BingoEntryState, BingoGridCell } from '../../model/BingoEntry';
const headerTitle = require("../../../assets/BingoHeaderMobile.svg")
require('./BingoMobileMiniGrid.scss');

type BingoMobileMiniGridProps = {
    cells: Array<BingoGridCell>,
    rows: number,
    columns: number,
    canVote: boolean,
    onSelectCell: (x: number, y: number) => void,
    selectedKey?: number,
}

export default function BingoMobileMiniGrid(props: BingoMobileMiniGridProps)
{
    function getCell(row: number, col: number)
    {
        return props.cells.find(c => c.row == row && c.col == col)
    }

    const cellSizeWithMargin = 900 / Math.max(props.columns, props.rows)
    const cellWidthWithMargin = 900 / props.columns
    const cellSize = cellSizeWithMargin-10
    const height = cellSizeWithMargin * props.rows + 180
    const seedStr = React.useMemo(() => `${props.columns}${props.rows}${props.cells.map(c => c.key).join('_')}`, [props.rows, props.columns])
    const rand = seededRand(seedStr)
    
    return (
        <svg className="mobileGrid" viewBox={`0 0 1000 ${height}`}>
            <defs>
            </defs>
            <rect className="gridBorder" x="10" y="10" width="980" height={height-20} rx="25" ry="25" />
            <image preserveAspectRatio="xMidYMid meet" x="50" y="0" width={900} height={125} href={headerTitle}/>
            <line className="gridBorder" x1="10" x2={990} y1="127.5" y2="127.5" />
            <g transform={"translate(50,155)"}>
                {
                    [...Array(props.rows).keys()].map(row => {
                        // let isRowComplete = gridContext.isRowComplete(row);
                        return [...Array(props.columns).keys()].map(col => {
                            // let isColComplete = gridContext.isColComplete(col);
                            let cell = getCell(row, col);
                            if (cell)
                            {
                                const isSelected = cell.key === props.selectedKey

                                var classes: string[] = Array();

                                switch (cell.state) {
                                    case BingoEntryState.Confirmed:
                                        classes.push("confirmed")
                                        break;
                                    case BingoEntryState.Idle:
                                        classes.push("idle")
                                        break;
                                    case BingoEntryState.Missed:
                                    case BingoEntryState.Rejected:
                                        classes.push("missed")
                                        break;
                                    case BingoEntryState.Pending:
                                        classes.push("pending")
                                        break;
                                    default:
                                        break;
                                }
                                if (isSelected)
                                {
                                    classes.push("highlighted")
                                }

                                var text = cell.key

                                const baseX = col*cellWidthWithMargin + (cellWidthWithMargin - cellSizeWithMargin)/2
                                const baseY = row*cellSizeWithMargin
                                const randX = rand()*(cellSize*0.250)-(cellSize*0.125)
                                const randY = rand()*(cellSize*0.250)-(cellSize*0.125)

                                const confirmationMark = cell.state == BingoEntryState.Confirmed ? (
                                    <circle cx={randX+baseX+cellSizeWithMargin/2} cy={randY+baseY+cellSizeWithMargin/2} r={cellSize/2.25} />
                                ) : null

                                return (
                                    <g className={classes.join(' ')} key={cell.key} style={{userSelect: 'none'}}>
                                        <rect
                                            className="background"
                                            x={baseX}
                                            y={baseY}
                                            width={cellSize}
                                            height={cellSize}
                                            rx={cellSize/5}
                                            ry={cellSize/5}
                                            onClickCapture={(_) => props.onSelectCell(col, row)}
                                        />
                                        <text x={baseX+cellSizeWithMargin/2} y={baseY+cellSizeWithMargin/2+cellSize/8} fontSize={cellSize/2}>{text}</text>
                                        { confirmationMark }
                                        <rect
                                            x={baseX}
                                            y={baseY}
                                            z="10"
                                            width={cellSize}
                                            height={cellSize}
                                            fill="rgba(255,255,255,0.0)"
                                            onClickCapture={(_) => props.onSelectCell(col, row)}
                                        />
                                    </g>)
                            }
                        })
                    })
                }
            </g>
        </svg>
    )
}

// twitch-bingo-extension/src/components/Mobile/BingoMobileMiniGrid.svelte
<script lang="ts">
    import { seededRand } from "../../common/ExtensionUtils";
    import { BingoEntryState, BingoGridCell } from "../../model/BingoEntry";
    const headerTitle = require("../../../assets/BingoHeaderMobile.svg")

    export let cells: Array<BingoGridCell> = new Array(0)
    export let rows: number
    export let columns: number
    export let canVote: boolean
    export let onSelectCell: (x: number, y: number) => void
    export let selectedKey: number | null = null

    function getCell(row: number, col: number)
    {
        return cells.find(c => c.row == row && c.col == col)
    }

    const cellSizeWithMargin = 900 / Math.max(columns, rows)
    const cellWidthWithMargin = 900 / columns
    const cellSize = cellSizeWithMargin-10
    const height = cellSizeWithMargin * rows + 180
    let seedStr: string = ""
    $: seedStr = `${columns}${rows}${cells.map(c => c.key).join('_')}`, [rows, columns]
    const rand = seededRand(seedStr)

    function getEntryInfos(row: number, col: number) {
        let cell = getCell(row, col)
        if (!cell) {
            return null
        }

        const isSelected = cell.key === selectedKey

        var classes: string[] = Array();

        switch (cell.state) {
            case BingoEntryState.Confirmed:
                classes.push("confirmed")
                break;
            case BingoEntryState.Idle:
                classes.push("idle")
                break;
            case BingoEntryState.Missed:
            case BingoEntryState.Rejected:
                classes.push("missed")
                break;
            case BingoEntryState.Pending:
                classes.push("pending")
                break;
            default:
                break;
        }
        if (isSelected)
        {
            classes.push("highlighted")
        }

        return {
            row: row,
            col: col,
            text: cell.key,
            cell: cell,
            classes: classes,
            baseX: col*cellWidthWithMargin + (cellWidthWithMargin - cellSizeWithMargin)/2,
            baseY: row*cellSizeWithMargin,
            randX: rand()*(cellSize*0.250)-(cellSize*0.125),
            randY: rand()*(cellSize*0.250)-(cellSize*0.125),
        }
    }

    const entriesInfos = [...Array(rows).keys()].map(row => [...Array(columns).keys()].map(col => getEntryInfos(row, col))).flat(1)
</script>

<style lang="scss">
    @use "./BingoMobileMiniGrid.scss"
</style>

<svg class="mobileGrid" viewBox={`0 0 1000 ${height}`}>
    <defs>
    </defs>
    <rect class="gridBorder" x="10" y="10" width="980" height={height-20} rx="25" ry="25" />
    <image preserveAspectRatio="xMidYMid meet" x="50" y="0" width={900} height={125} href={headerTitle}/>
    <line class="gridBorder" x1="10" x2={990} y1="127.5" y2="127.5" />
    <g transform="translate(50,155)">
        {#each entriesInfos as entryInfo}
            {#if entryInfo}
                <!-- svelte-ignore a11y-click-events-have-key-events -->
                <g class={entryInfo.classes.join(' ')} style="user-select: 'none';">
                    <!-- svelte-ignore a11y-click-events-have-key-events -->
                    <!-- svelte-ignore a11y-no-static-element-interactions -->
                    <rect
                        class="background"
                        x={entryInfo.baseX}
                        y={entryInfo.baseY}
                        width={cellSize}
                        height={cellSize}
                        rx={cellSize/5}
                        ry={cellSize/5}
                        on:click|capture={(_) => onSelectCell(entryInfo.col, entryInfo.row)}
                    />
                    <text x={entryInfo.baseX+cellSizeWithMargin/2} y={entryInfo.baseY+cellSizeWithMargin/2+cellSize/8} font-size={cellSize/2}>{entryInfo.text}</text>
                    {#if entryInfo.cell.state == BingoEntryState.Confirmed}
                        <circle cx={entryInfo.randX+entryInfo.baseX+cellSizeWithMargin/2}
                                cy={entryInfo.randY+entryInfo.baseY+cellSizeWithMargin/2}
                                r={cellSize/2.25} />
                    {/if}
                    <!-- svelte-ignore a11y-click-events-have-key-events -->
                    <!-- svelte-ignore a11y-no-static-element-interactions -->
                    <rect
                        x={entryInfo.baseX}
                        y={entryInfo.baseY}
                        z="10"
                        width={cellSize}
                        height={cellSize}
                        fill="rgba(255,255,255,0.0)"
                        on:click|capture={(_) => onSelectCell(entryInfo.col, entryInfo.row)}
                    />
                </g>
            {/if}
        {/each}
    </g>
</svg>
