// twitch-bingo-extension/src/Config.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { GetCurrentLanguage } from './common/ExtensionUtils';
import Config from './components/Config/Config'
import TypesafeI18n from './i18n/i18n-react'

ReactDOM.render(
    <TypesafeI18n initialLocale={GetCurrentLanguage()}>
        <Config />
    </TypesafeI18n>,
    document.getElementById("root") as HTMLElement
);

// twitch-bingo-extension/src/Config.svelte
<script lang="ts">
    import ConfigurationRoot from "./components/Config/Config.svelte"
    import { GetCurrentLanguage } from './common/ExtensionUtils'
    import { setLocale } from './i18n/i18n-svelte'
    import { onMount } from "svelte";
    import { loadLocaleAsync } from "./i18n/i18n-util.async";

    onMount(async () => {
        const currentLocale = GetCurrentLanguage()
        await loadLocaleAsync(currentLocale)
        setLocale(currentLocale)
    })

</script>
  
<ConfigurationRoot />
