// twitch-bingo-extension/src/LiveConfig.svelte
<script lang="ts">
    import LiveConfigRoot from "./components/LiveConfig/LiveConfig.svelte"
    import { GetCurrentLanguage } from './common/ExtensionUtils'
    import { setLocale } from './i18n/i18n-svelte'
    import { onMount } from "svelte";
    import { loadLocaleAsync } from "./i18n/i18n-util.async";

    onMount(async () => {
        const currentLocale = GetCurrentLanguage()
        await loadLocaleAsync(currentLocale)
        setLocale(currentLocale)
    })

</script>
  
<LiveConfigRoot />

// twitch-bingo-extension/src/LiveConfig.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { GetCurrentLanguage } from './common/ExtensionUtils';
import LiveConfig from './components/LiveConfig/LiveConfig'
import TypesafeI18n from './i18n/i18n-react'

ReactDOM.render(
    <TypesafeI18n locale={GetCurrentLanguage()}>
        <LiveConfig />
    </TypesafeI18n>,
    document.getElementById("root") as HTMLElement
);
