// twitch-bingo-extension/src/Mobile.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { GetCurrentLanguage } from './common/ExtensionUtils';
import Mobile from './components/Mobile/Mobile'
import TypesafeI18n from './i18n/i18n-react'

ReactDOM.render(
    <TypesafeI18n locale={GetCurrentLanguage()}>
        <Mobile />
    </TypesafeI18n>,
    document.getElementById("root") as HTMLElement
);

// twitch-bingo-extension/src/Mobile.svelte
<script lang="ts">
    import Mobile from './components/Mobile/Mobile.svelte'
    import { GetCurrentLanguage } from './common/ExtensionUtils'
    import { setLocale } from './i18n/i18n-svelte'
    import { onMount } from "svelte";
    import { loadLocaleAsync } from "./i18n/i18n-util.async";

    onMount(async () => {
        const currentLocale = GetCurrentLanguage()
        await loadLocaleAsync(currentLocale)
        setLocale(currentLocale)
    })
</script>

<Mobile />
