// twitch-bingo-extension/src/VideoOverlay.svelte
<script lang="ts">
    import VideoOverlay from './components/VideoOverlay/VideoOverlay.svelte'  
    import { GetCurrentLanguage } from './common/ExtensionUtils'
    import { setLocale } from './i18n/i18n-svelte'
    import { onMount } from "svelte";
    import { loadLocaleAsync } from "./i18n/i18n-util.async";

    onMount(async () => {
        const currentLocale = GetCurrentLanguage()
        await loadLocaleAsync(currentLocale)
        setLocale(currentLocale)
    })
</script>

<VideoOverlay />

// twitch-bingo-extension/src/VideoOverlay.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { GetCurrentLanguage } from './common/ExtensionUtils';
import VideoOverlay from './components/VideoOverlay/VideoOverlay'
import TypesafeI18n from './i18n/i18n-react'

ReactDOM.render(
    <TypesafeI18n initialLocale={GetCurrentLanguage()}>
        <VideoOverlay />
    </TypesafeI18n>,
    document.getElementById("root") as HTMLElement
);
