// twitch-bingo-extension/src/components/Config/EntrySelectionView.tsx
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import CardHeader from '@material-ui/core/CardHeader';
import Icon from '@material-ui/core/Icon';
import IconButton from '@material-ui/core/IconButton';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemText from '@material-ui/core/ListItemText';
import Typography from '@material-ui/core/Typography';
import RemoveCircleOutline from '@material-ui/icons/RemoveCircleOutline';
import React from 'react'
import { I18nContext } from '../../i18n/i18n-react';
import { BingoEditableEntry } from '../../model/BingoEntry';

type EntrySelectionViewProps = {
    entries: BingoEditableEntry[],
    selectedEntries: number[],
    onAddToSelection: (entry: BingoEditableEntry) => void,
    onRemoveFromSelection: (entry: BingoEditableEntry) => void,
}

export default function EntrySelectionView(props:EntrySelectionViewProps)
{
    const { LL } = React.useContext(I18nContext)
    
    var targetListElement: JSX.Element = null;
    if (props.selectedEntries.length == 0)
    {
        targetListElement = <Typography><em>{LL.Config.EntrySelectionView.NoItemMessage()}</em></Typography>
    }
    else
    {
        targetListElement = <List>
            {
                props.selectedEntries.map((key, index) => {
                    var entry:BingoEditableEntry = props.entries.find(b => b.key == key);
                    return <ListItem button onClick={() => props.onRemoveFromSelection(entry)} key={key}>
                        <ListItemText
                            primary={`${index}) ${entry.text}`}
                        />
                        <IconButton onClickCapture={() => props.onRemoveFromSelection(entry)} size="small">
                            <Icon>
                                <RemoveCircleOutline />
                            </Icon>
                        </IconButton>
                    </ListItem>
                })
            }
        </List>;
    }

    return (
        <Card>
            <CardHeader title={LL.Config.EntrySelectionView.Title()} subheader={LL.Config.EntrySelectionView.TitleSubHeader()} />
            <CardContent>
                { targetListElement }
            </CardContent>
        </Card>
    )
}

// twitch-bingo-extension/src/components/Config/EntrySelectionView.svelte
<script lang="ts">
    import LL from '../../i18n/i18n-svelte';
    import { Icon } from "@smui/button";
    import Card, { Content } from "@smui/card";
    import type { BingoEditableEntry } from "src/model/BingoEntry";
    import List, { Item, Text, Meta } from '@smui/list';
    import IconButton from '@smui/icon-button';

    export let entries: BingoEditableEntry[]
    export let selectedEntries: number[]
    export let onAddToSelection: (entry: BingoEditableEntry) => void
    export let onRemoveFromSelection: (entry: BingoEditableEntry) => void

    function onRemoveFromSelectionKey(key: number) {
        onRemoveFromSelection(getEntry(key))
    }

    function getEntry(key: number){
        return entries.find(b => b.key == key)
    }
</script>

<Card>
    <Content>
        <h2 class="mdc-typography--headline6">{$LL.Config.EntrySelectionView.Title()}</h2>
        <h3 class="mdc-typography--subtitle2">{$LL.Config.EntrySelectionView.TitleSubHeader()}</h3>
        {#if selectedEntries.length == 0}
        <span><em>{$LL.Config.EntrySelectionView.NoItemMessage()}</em></span>
        {:else}
        <List>
            {#each selectedEntries as key, index (key)}
                <Item on:click={() => onRemoveFromSelectionKey(key)}>
                    <Text>{`${index}) ${getEntry(key).text}`}</Text>
                </Item>
                <Meta>
                    <IconButton on:click={() => onRemoveFromSelectionKey(key)} sizes="small">
                        <Icon class="material-icons">do_not_disturb_on</Icon>
                    </IconButton>
                </Meta>
            {/each}
        </List>
        {/if}
    </Content>
</Card>
