// twitch-bingo-extension/src/components/Config/GridConfigurationView.tsx
import Box from '@material-ui/core/Box'
import Button from '@material-ui/core/Button'
import Card from '@material-ui/core/Card'
import CardActions from '@material-ui/core/CardActions'
import CardContent from '@material-ui/core/CardContent'
import CardHeader from '@material-ui/core/CardHeader'
import Grid from '@material-ui/core/Grid'
import Paper from '@material-ui/core/Paper'
import Slider from '@material-ui/core/Slider'
import Typography from '@material-ui/core/Typography'
import Alert from '@material-ui/lab/Alert'
import AlertTitle from '@material-ui/lab/AlertTitle'
import React from 'react'
import { FormatTimeout } from '../../EBS/BingoService/EBSBingoTypes'
import { I18nContext } from '../../i18n/i18n-react'

type GridConfigurationViewProps = {
    columns: number;
    rows: number;
    confirmationThresholdSeconds: number;
    selectedEntriesLength: number;
    onColumnsChange: (value: number) => void;
    onRowsChange: (value: number) => void;
    onConfirmationTimeoutChange: (value: number) => void;
    onSave: () => void;
    onStart: () => void;
    isStarting: boolean;
}

export default function GridConfigurationView(props:GridConfigurationViewProps)
{
    const { LL } = React.useContext(I18nContext)

    const hasEnoughEntries = (): boolean => props.selectedEntriesLength >= props.rows * props.columns
    const canStart = (): boolean => !props.isStarting && hasEnoughEntries()

    return (
        <Card>
            <CardHeader title={LL.Config.ConfigureGrid()} />
            <CardContent>
                <Typography>
                    {LL.Config.Columns()}
                </Typography>
                <Slider
                    defaultValue={3}
                    step={1}
                    min={2}
                    marks
                    max={5}
                    valueLabelDisplay="auto"
                    value={props.columns}
                    onChange={(_, value) => props.onColumnsChange(value as number)}
                />
                <Typography>
                    {LL.Config.Rows()}
                </Typography>
                <Slider
                    defaultValue={3}
                    step={1}
                    min={2}
                    marks
                    max={5}
                    valueLabelDisplay="auto"
                    value={props.rows}
                    onChange={(_, value) => props.onRowsChange(value as number)}
                />
                { !hasEnoughEntries() ? 
                    <Alert severity="error">
                        <AlertTitle>{LL.Config.AlertNotEnoughEntriesToFillTheGrid()}</AlertTitle>
                        {LL.Config.AddEntriesOrReduceGridDimensionsToStartTheGame()}
                    </Alert>
                     : null }
                <Grid container>
                {
                    [...Array(props.rows).keys()].map(r => {
                        return <Grid container item xs={12} spacing={1} key={r}>
                            {
                                [...Array(props.columns).keys()].map(c => {
                                    return <Grid item xs key={c}>
                                        <Paper className="paper" elevation={3}>
                                            <Box py={2} my={0.5} bgcolor={ (r * props.columns + c) < props.selectedEntriesLength ? "primary.main" : "error.main" }>
                                                <Typography>
                                                    
                                                </Typography>
                                            </Box>
                                        </Paper>
                                    </Grid>
                                })
                            }
                        </Grid>
                    })
                }
                </Grid>
                <Typography>
                    {LL.Config.ConfirmationTime()}
                </Typography>
                <Slider
                    defaultValue={120}
                    step={10}
                    min={30}
                    marks
                    max={300}
                    valueLabelDisplay="auto"
                    valueLabelFormat={FormatTimeout(props.confirmationThresholdSeconds)}
                    value={props.confirmationThresholdSeconds}
                    onChange={(_, value) => props.onConfirmationTimeoutChange(value as number)}
                />
            </CardContent>
            <CardActions>
                <Button variant="contained" color="primary" onClick={props.onSave}>
                    {LL.Config.SaveGame()}
                </Button>
                <Button variant="contained" color="primary" onClick={props.onStart} disabled={!canStart()}>
                    {LL.Config.StartGame()}
                </Button>
            </CardActions>
        </Card>
    )
}

// twitch-bingo-extension/src/components/Config/GridConfigurationView.svelte
<script lang="ts">
    import Card, { Actions, Content } from '@smui/card';
    import LayoutGrid, { Cell } from '@smui/layout-grid'
    import Slider from '@smui/slider'
    import { onMount } from 'svelte';
    import Paper from '@smui/paper'
    import Alert from '../../common/Alert.svelte'
    import LL from '../../i18n/i18n-svelte';
    import { FormatTimeout } from '../../EBS/BingoService/EBSBingoTypes';
    import Button from '@smui/button';

    export let columns: number
    export let rows : number
    export let confirmationThresholdSeconds: number
    export let selectedEntriesLength: number
    export let onColumnsChange: (value: number) => void
    export let onRowsChange: (value: number) => void
    export let onConfirmationTimeoutChange: (value: number) => void
    export let onSave: () => void
    export let onStart: () => void
    export let isStarting: boolean
    export let canEnableChat: boolean

    let editingColumns: number = 3
    let editingRows: number = 3
    let confirmationTimeout: number = 120

    onMount(() => {
        editingColumns = columns
        editingRows = rows
        confirmationTimeout = confirmationThresholdSeconds
    })

    $: hasEnoughEntries = selectedEntriesLength >= rows * columns
    $: canStart = !isStarting && hasEnoughEntries

    $: {
        onColumnsChange(editingColumns)
    }
    $: {
        onRowsChange(editingRows)
    }
    $: {
        onConfirmationTimeoutChange(confirmationTimeout)
    }
</script>

<Card>
    <Content>
        <h2>{$LL.Config.ConfigureGrid()}</h2>
        <span>
            {$LL.Config.Columns()}
        </span>
        <Slider
            defaultValue={3}
            step={1}
            min={2}
            tickMarks
            max={5}
            bind:value={editingColumns}
        />
        <span>
            {$LL.Config.Rows()}
        </span>
        <Slider
            defaultValue={3}
            step={1}
            min={2}
            tickMarks
            max={5}
            bind:value={editingRows}
        />
        {#if !hasEnoughEntries}
        <Alert severity="error">
            <h2 slot="title">{$LL.Config.AlertNotEnoughEntriesToFillTheGrid()}</h2>
            <svelte:fragment slot="body">
                {$LL.Config.AddEntriesOrReduceGridDimensionsToStartTheGame()}
            </svelte:fragment>
        </Alert>
        {/if}
        <LayoutGrid container>
            {#each [...Array(rows).keys()] as r}
            <LayoutGrid container item xs={12} spacing={1} key={r}>
                {#each [...Array(columns).keys()] as c}
                <Cell item xs key={c}>
                    <Paper className="paper" elevation={3}>
                        <div style={"background-color: " + ((r * columns + c) < selectedEntriesLength) ? "primary.main" : "error.main"}>
                            &nbsp;
                        </div>
                    </Paper>
                </Cell>
                {/each}
            </LayoutGrid>
            {/each}
        </LayoutGrid>
        <span>
            {$LL.Config.ConfirmationTime()}
        </span>
        <Slider
            defaultValue={120}
            step={10}
            min={30}
            tickmMarks
            max={300}
            valueLabelDisplay="auto"
            valueLabelFormat={FormatTimeout(confirmationTimeout)}
            bind:value={confirmationTimeout}
        />
        <div>
            {#if canEnableChat}
            <Alert severity="info">
                <h2 slot="title">{$LL.Config.DeactivateChatIntegrationTitle()}</h2>
                <svelte:fragment slot="body">
                    {$LL.Config.DeactivateChatIntegrationText()}
                </svelte:fragment>
            </Alert>
            {:else}
            <Alert severity="warning">
                <h2 slot="title">{$LL.Config.ActivateChatIntegrationTitle()}</h2>
                <svelte:fragment slot="body">
                    {$LL.Config.ActivateChatIntegrationText()}
                </svelte:fragment>
            </Alert>
            {/if}
        </div>
    </Content>
    <Actions>
        <Button variant="unelevated" color="primary" onClick={onSave}>
            {$LL.Config.SaveGame()}
        </Button>
        <Button variant="unelevated" color="primary" onClick={onStart} disabled={!canStart}>
            {$LL.Config.StartGame()}
        </Button>
    </Actions>
</Card>
