// twitch-bingo-extension/src/components/Config/StatusCard.svelte
<script lang="ts">
import Card, { Content, Actions } from "@smui/card"
import Button, { Icon } from "@smui/button"
import IconButton from "@smui/icon-button"
import LinearProgress from '@smui/linear-progress'
import type { BingoEntry, BingoLogEntry } from "../../EBS/BingoService/EBSBingoTypes";
import GameLogView from "./GameLogView.svelte";
import LL from "../../i18n/i18n-svelte";

export let isLoading: boolean
export let isActive: boolean
export let entries: BingoEntry[] | undefined
export let logEntries: BingoLogEntry[]
export let isLoadingLog: boolean
export let onRefreshLog: () => void
export let onStop: () => void
</script>

<Card>
    <div style="padding: 1rem;">
        <h2 class="mdc-typography--headline6" style="margin: 0;">
            {$LL.Config.StatusCard.Title()}
        </h2>
    </div>
    <Content>
        {#if isLoading}
        <div style="margin: '1vw'">
            <LinearProgress indeterminate />
            <div class='mdc-typography--body1'>{$LL.Config.StatusCard.LoadingConfiguration()}</div>
        </div>
        {:else if isActive === true}
        <h2 class="mdc-typography--h5">{$LL.Config.StatusCard.StatusActive()}</h2>
        {:else}
        <h2 class="mdc-typography--h5">{$LL.Config.StatusCard.StatusInactive()}</h2>
        {/if}
    </Content>
    <Actions>
        {#if isActive}
            <Button variant="unelevated" color="secondary" on:click={onStop}>{$LL.Config.StatusCard.StopButton()}</Button>
        {/if}
    </Actions>
    <Content>
        {#if !isLoading && isActive}
        <h2 class="mdc-typography--h5">
            {$LL.Config.GameLog.Header()}
            <IconButton on:click={onRefreshLog} disabled={isLoadingLog}>
                <Icon class="material-icons">refresh</Icon>
            </IconButton>
        </h2>
        <GameLogView
            isLoading={isLoadingLog && logEntries.length == 0}
            entries={entries ?? []}
            logEntries={logEntries} />
        {/if}
    </Content>
</Card>

// twitch-bingo-extension/src/components/Config/StatusCard.tsx
import { Box, IconButton, LinearProgress } from '@material-ui/core'
import Button from '@material-ui/core/Button'
import Card from '@material-ui/core/Card'
import CardActions from '@material-ui/core/CardActions'
import CardContent from '@material-ui/core/CardContent'
import CardHeader from '@material-ui/core/CardHeader'
import Typography from '@material-ui/core/Typography'
import React from 'react'
import { BingoEntry, BingoLogEntry } from '../../EBS/BingoService/EBSBingoTypes'
import { I18nContext } from '../../i18n/i18n-react'
import GameLogView from './GameLogView'
import RefreshIcon from '@material-ui/icons/Refresh'

type StatusCardProps = {
    isLoading: boolean;
    isActive: boolean;
    entries: BingoEntry[];
    logEntries: BingoLogEntry[];
    isLoadingLog: boolean;
    onRefreshLog: () => void;
    onStop: () => void;
}

export default function StatusCard(props: StatusCardProps)
{
    const { LL } = React.useContext(I18nContext)

    return (
        <Card>
            <CardHeader title={LL.Config.StatusCard.Title()} />
            <CardContent>
                {
                    props.isLoading ?
                        <Box style={{ margin: '1vw' }}>
                            <LinearProgress variant="indeterminate" />
                            <Typography align='center'>{LL.Config.StatusCard.LoadingConfiguration()}</Typography>
                        </Box> :
                            props.isActive === true ?
                            <Typography variant="h5" component="h2">{LL.Config.StatusCard.StatusActive()}</Typography> :
                            <Typography variant="h5" component="h2">{LL.Config.StatusCard.StatusInactive()}</Typography>
                }
            </CardContent>
            <CardActions>
                {
                    props.isActive ? <Button variant="contained" color="secondary" onClick={props.onStop}>{LL.Config.StatusCard.StopButton()}</Button> : null
                }
            </CardActions>
            <CardContent>
                {
                    (!props.isLoading && props.isActive) ? (
                        <React.Fragment>
                            <Typography gutterBottom variant="h5" component="h2">
                                {LL.Config.GameLog.Header()}
                                <IconButton onClick={props.onRefreshLog} disabled={props.isLoadingLog}>
                                    <RefreshIcon />
                                </IconButton>
                            </Typography>
                            <GameLogView
                                isLoading={props.isLoadingLog && props.logEntries.length == 0}
                                entries={props.entries}
                                logEntries={props.logEntries} />
                        </React.Fragment>
                    ) : null
                }
            </CardContent>
        </Card>
    )
}
